// app02_angular/frontend/src/app/features/dashboard/dashboard.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatIconModule } from '@angular/material/icon';
import { catchError, of } from 'rxjs';

import { FrameworkService } from '../../core/services/framework.service';
import { ThreatService } from '../../core/services/threat.service';
import { Framework } from '../../shared/models/framework.model';

@Component({
  selector: 'tv-dashboard',
  standalone: true,
  imports: [MatCardModule, MatFormFieldModule, MatInputModule, MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h1>ThreatView 2026</h1>
    <p class="subtitle">
      Interaktywna baza zagrożeń, mitigacji i przykładów kodu w OWASP, MITRE ATLAS i CompTIA SecAI+.
    </p>

    @if (loadFailed()) {
      <div class="error-banner">
        Nie udało się połączyć z API. Sprawdź, czy backend działa na porcie 8080 (<code>docker compose up</code>).
      </div>
    }

    <div class="stats">
      <mat-card>
        <mat-card-subtitle>Frameworki bezpieczeństwa</mat-card-subtitle>
        <mat-card-title>{{ frameworks().length }}</mat-card-title>
      </mat-card>
      <mat-card>
        <mat-card-subtitle>Zagrożenia w katalogu</mat-card-subtitle>
        <mat-card-title>{{ threatCount() ?? '—' }}</mat-card-title>
      </mat-card>
    </div>

    <mat-form-field appearance="outline" class="search">
      <mat-label>Szybkie wyszukiwanie, np. prompt injection...</mat-label>
      <input matInput [value]="query()" (input)="query.set($any($event.target).value)" />
      <mat-icon matSuffix>search</mat-icon>
    </mat-form-field>

    <h2>Frameworki</h2>
    <div class="framework-grid">
      @for (framework of filteredFrameworks(); track framework.code) {
        <mat-card class="framework-card">
          <mat-card-subtitle>{{ framework.code }}</mat-card-subtitle>
          <mat-card-title>{{ framework.name }}</mat-card-title>
          <mat-card-content>{{ framework.version }}</mat-card-content>
        </mat-card>
      } @empty {
        <p class="muted">Brak frameworków spełniających wyszukiwanie.</p>
      }
    </div>
  `,
  styles: [
    `
      .subtitle {
        color: #666;
        max-width: 640px;
      }
      .error-banner {
        background: #fdecea;
        border: 1px solid #f5c6cb;
        color: #611a15;
        padding: 12px 16px;
        border-radius: 4px;
        margin-bottom: 16px;
      }
      .stats {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 16px;
        margin-bottom: 24px;
      }
      .search {
        width: 100%;
        max-width: 480px;
        display: block;
        margin-bottom: 24px;
      }
      .framework-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
        gap: 16px;
      }
      .muted {
        color: #888;
      }
    `,
  ],
})
export class DashboardComponent {
  private readonly frameworkService = inject(FrameworkService);
  private readonly threatService = inject(ThreatService);

  readonly query = signal('');
  readonly loadFailed = signal(false);

  private readonly frameworksResult = toSignal(
    this.frameworkService.getFrameworks().pipe(
      catchError(() => {
        this.loadFailed.set(true);
        return of<Framework[]>([]);
      }),
    ),
    { initialValue: [] as Framework[] },
  );

  readonly frameworks = computed(() => this.frameworksResult());

  readonly filteredFrameworks = computed(() => {
    const q = this.query().trim().toLowerCase();
    if (!q) return this.frameworks();
    return this.frameworks().filter(
      (f) => f.name.toLowerCase().includes(q) || f.code.toLowerCase().includes(q),
    );
  });

  private readonly threatCountResult = toSignal(
    this.threatService.search({ size: 1 }).pipe(
      catchError(() => of(null)),
    ),
    { initialValue: null },
  );

  readonly threatCount = computed(() => this.threatCountResult()?.totalElements ?? null);
}

// app04_scala_react/frontend/src/pages/Dashboard.tsx
import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api } from '@/api/client'
import type { Framework } from '@/types'

export default function Dashboard() {
  const [frameworks, setFrameworks] = useState<Framework[]>([])
  const [threatCount, setThreatCount] = useState<number | null>(null)
  const [query, setQuery] = useState('')
  const [loadError, setLoadError] = useState<string | null>(null)
  const navigate = useNavigate()

  useEffect(() => {
    api.getFrameworks().then(setFrameworks).catch(() => setLoadError('Nie udało się połączyć z API.'))
    api.getThreats({ size: 1 }).then((page) => setThreatCount(page.totalElements)).catch(() => {})
  }, [])

  function handleSearch(e: React.FormEvent) {
    e.preventDefault()
    if (query.trim()) navigate(`/frameworks?q=${encodeURIComponent(query.trim())}`)
  }

  return (
    <div className="space-y-8">
      <section>
        <h1 className="text-3xl font-bold text-white">ScalaShield 2026</h1>
        <p className="mt-2 max-w-2xl text-slate-400">
          Interaktywna baza zagrożeń, mitigacji i przykładów kodu w OWASP, MITRE ATLAS i CompTIA SecAI+.
        </p>
      </section>

      {loadError && (
        <p className="rounded-md border border-red-900 bg-red-950 px-4 py-3 text-sm text-red-300">
          {loadError} Sprawdź, czy backend działa na porcie 8080 (`docker compose up`).
        </p>
      )}

      <section className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        <div className="rounded-lg border border-slate-800 bg-slate-900 p-6">
          <div className="text-sm text-slate-400">Frameworki bezpieczeństwa</div>
          <div className="mt-1 text-3xl font-bold text-white">{frameworks.length}</div>
        </div>
        <div className="rounded-lg border border-slate-800 bg-slate-900 p-6">
          <div className="text-sm text-slate-400">Zagrożenia w katalogu</div>
          <div className="mt-1 text-3xl font-bold text-white">{threatCount ?? '—'}</div>
        </div>
      </section>

      <form onSubmit={handleSearch} className="flex gap-2">
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Szybkie wyszukiwanie, np. prompt injection..."
          className="w-full rounded-md border border-slate-700 bg-slate-900 px-4 py-2 text-slate-100 placeholder-slate-500 focus:border-slate-500 focus:outline-none"
        />
        <button type="submit" className="rounded-md bg-slate-100 px-4 py-2 font-medium text-slate-900 hover:bg-white">
          Szukaj
        </button>
      </form>

      <section>
        <h2 className="mb-3 text-lg font-semibold text-white">Frameworki</h2>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {frameworks.map((f) => (
            <Link
              key={f.code}
              to={`/frameworks/${f.code}`}
              className="rounded-lg border border-slate-800 bg-slate-900 p-4 transition-colors hover:border-slate-600"
            >
              <div className="font-medium text-white">{f.name}</div>
              <div className="text-sm text-slate-400">{f.version}</div>
            </Link>
          ))}
        </div>
      </section>
    </div>
  )
}
